#!/usr/bin/env python3
"""Generate Sprout character assets by recoloring Clippy animations.

This script reads the existing Clippy APNG animation files from
src/renderer/images/animations/, applies a plant/garden green color
palette, and writes the resulting Sprout animation files to
src/renderer/images/animations/sprout/.

It also generates the corresponding TypeScript animation module at
src/renderer/sprout-animations.tsx.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Tuple

import numpy as np
from PIL import Image, ImageFilter

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CLIPPY_ANIMATIONS_DIR = PROJECT_ROOT / "src" / "renderer" / "images" / "animations"
SPROUT_OUTPUT_DIR = CLIPPY_ANIMATIONS_DIR / "sprout"
SPROUT_TSX_FILE = PROJECT_ROOT / "src" / "renderer" / "sprout-animations.tsx"
SPROUT_ANIMATIONS_JSON = (
    PROJECT_ROOT / "assets" / "animations" / "clippy" / "animations.json"
)
SPROUT_ASSETS_DIR = PROJECT_ROOT / "assets" / "animations" / "sprout"

# Shadow → highlight green palette (R, G, B)
SHADOW_COLOR = np.array([30, 70, 20], dtype=np.float32)      # deep forest green
MIDTONE_COLOR = np.array([70, 170, 70], dtype=np.float32)    # fresh leaf green
HIGHLIGHT_COLOR = np.array([190, 250, 150], dtype=np.float32) # vibrant lime highlight
EYE_BLACK = np.array([5, 5, 5], dtype=np.float32)
EYE_WHITE = np.array([255, 255, 255], dtype=np.float32)

# Output display width in pixels — matches Sprout.tsx `width: "124px"`
OUTPUT_WIDTH = 124

# Light unsharp mask after LANCZOS downscale to recover edge crispness
UNSHARP_MASK = ImageFilter.UnsharpMask(radius=0.6, percent=130, threshold=3)


def recolor_frame(frame: Image.Image) -> Image.Image:
    """Recolor a single frame using numpy vectorized operations.

    Maps Clippy's beige/tan palette to Sprout's green palette via luminance,
    preserving eye-black and eye-white regions.
    """
    arr = np.array(frame.convert("RGBA"), dtype=np.float32)
    r, g, b, a = arr[:, :, 0], arr[:, :, 1], arr[:, :, 2], arr[:, :, 3]

    lum = 0.299 * r + 0.587 * g + 0.114 * b
    t = lum / 255.0

    transparent = a < 10
    eye_black = ~transparent & (lum < 35)
    eye_white = ~transparent & (lum > 245)
    shadow_region = ~transparent & ~eye_black & ~eye_white & (t < 0.4)
    highlight_region = ~transparent & ~eye_black & ~eye_white & (t >= 0.4)

    out = arr.copy()

    # Eye preservation
    for ch in range(3):
        out[:, :, ch] = np.where(eye_black, EYE_BLACK[ch], out[:, :, ch])
        out[:, :, ch] = np.where(eye_white, EYE_WHITE[ch], out[:, :, ch])

    # Shadow band: lerp(SHADOW, MIDTONE, t/0.4)
    local_t = np.clip(t / 0.4, 0.0, 1.0)
    for ch in range(3):
        blended = SHADOW_COLOR[ch] + (MIDTONE_COLOR[ch] - SHADOW_COLOR[ch]) * local_t
        out[:, :, ch] = np.where(shadow_region, blended, out[:, :, ch])

    # Highlight band: lerp(MIDTONE, HIGHLIGHT, (t-0.4)/0.6)
    local_t = np.clip((t - 0.4) / 0.6, 0.0, 1.0)
    for ch in range(3):
        blended = MIDTONE_COLOR[ch] + (HIGHLIGHT_COLOR[ch] - MIDTONE_COLOR[ch]) * local_t
        out[:, :, ch] = np.where(highlight_region, blended, out[:, :, ch])

    return Image.fromarray(out.clip(0, 255).astype(np.uint8), "RGBA")


def scale_and_sharpen(frame: Image.Image) -> Image.Image:
    """Downscale to OUTPUT_WIDTH using LANCZOS, then apply light unsharp mask."""
    src_w, src_h = frame.size
    out_h = round(src_h * OUTPUT_WIDTH / src_w)
    scaled = frame.resize((OUTPUT_WIDTH, out_h), Image.LANCZOS)
    return scaled.filter(UNSHARP_MASK)


def recolor_apng(source_path: Path, dest_path: Path) -> int:
    """Recolor and downscale an APNG file and save it. Returns total duration in ms."""
    source = Image.open(source_path)
    frames: list[Image.Image] = []
    durations: list[int] = []
    total_duration = 0

    for frame_index in range(getattr(source, "n_frames", 1)):
        source.seek(frame_index)
        recolored = recolor_frame(source)
        frames.append(scale_and_sharpen(recolored))
        duration = int(source.info.get("duration", 100))
        durations.append(duration)
        total_duration += duration

    if len(frames) == 1:
        frames[0].save(dest_path, format="PNG")
    else:
        frames[0].save(
            dest_path,
            format="PNG",
            save_all=True,
            append_images=frames[1:],
            duration=durations,
            loop=0,
        )

    return total_duration


def safe_import_name(name: str) -> str:
    """Convert a filename to a valid TypeScript identifier."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def generate_sprout_tsx(durations: dict[str, int]) -> str:
    """Generate the Sprout animations TypeScript module."""
    lines: list[str] = [
        "// This file is auto-generated by tools/generate-sprout-assets.py",
        "",
        "export interface Animation {",
        "  src: string;",
        "  length: number;",
        "}",
        "",
    ]

    names = sorted(durations.keys())
    for name in names:
        import_name = safe_import_name(name)
        lines.append(f'import {import_name} from "./images/animations/sprout/{name}.png";')

    lines.append("")
    lines.append("export const SPROUT_ANIMATIONS: Record<string, Animation> = {")

    for name in names:
        import_name = safe_import_name(name)
        display_name = name.replace("_", " ")
        lines.append(f"  '{display_name}': {{")
        lines.append(f"    src: {import_name},")
        lines.append(f"    length: {durations[name]},")
        lines.append("  },")

    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not CLIPPY_ANIMATIONS_DIR.exists():
        print(f"Clippy animations directory not found: {CLIPPY_ANIMATIONS_DIR}")
        return 1

    SPROUT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    SPROUT_ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    # Copy the source animation manifest for reference
    if SPROUT_ANIMATIONS_JSON.exists():
        with open(SPROUT_ANIMATIONS_JSON, "r", encoding="utf-8") as f:
            manifest = json.load(f)
        sprout_manifest_path = SPROUT_ASSETS_DIR / "animations.json"
        with open(sprout_manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)

    durations: dict[str, int] = {}
    png_files = sorted(
        p for p in CLIPPY_ANIMATIONS_DIR.iterdir()
        if p.is_file() and p.suffix.lower() == ".png"
    )

    for source_path in png_files:
        dest_path = SPROUT_OUTPUT_DIR / source_path.name
        print(f"Processing {source_path.name}...")
        total_duration = recolor_apng(source_path, dest_path)
        durations[source_path.stem] = total_duration

    tsx_content = generate_sprout_tsx(durations)
    with open(SPROUT_TSX_FILE, "w", encoding="utf-8") as f:
        f.write(tsx_content)

    print(f"Generated {len(durations)} Sprout animations in {SPROUT_OUTPUT_DIR}")
    print(f"Generated TypeScript module at {SPROUT_TSX_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
