#!/usr/bin/env python3
"""Generate Sprout character assets by recoloring Clippy animations.

This script reads the existing Clippy APNG animation files from
src/renderer/images/animations/, applies a plant/garden green color
palette, and writes the resulting Sprout animation files to
src/renderer/images/animations/sprout/.

It also generates the corresponding TypeScript animation module at
src/renderer/sprout-animations.tsx.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Tuple

from PIL import Image

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CLIPPY_ANIMATIONS_DIR = PROJECT_ROOT / "src" / "renderer" / "images" / "animations"
SPROUT_OUTPUT_DIR = CLIPPY_ANIMATIONS_DIR / "sprout"
SPROUT_TSX_FILE = PROJECT_ROOT / "src" / "renderer" / "sprout-animations.tsx"
SPROUT_ANIMATIONS_JSON = (
    PROJECT_ROOT / "assets" / "animations" / "clippy" / "animations.json"
)
SPROUT_ASSETS_DIR = PROJECT_ROOT / "assets" / "animations" / "sprout"

# Shadow → highlight green palette (R, G, B)
SHADOW_COLOR = (30, 70, 20)      # deep forest green
MIDTONE_COLOR = (70, 170, 70)    # fresh leaf green
HIGHLIGHT_COLOR = (190, 250, 150)  # vibrant lime highlight
EYE_WHITE = (255, 255, 255)
EYE_BLACK = (5, 5, 5)


def lerp_color(c1: Tuple[int, int, int], c2: Tuple[int, int, int], t: float) -> Tuple[int, int, int]:
    """Linearly interpolate between two RGB colors."""
    return tuple(int(a + (b - a) * t) for a, b in zip(c1, c2))  # type: ignore[return-value]


def recolor_pixel(r: int, g: int, b: int, a: int) -> Tuple[int, int, int, int]:
    """Map a Clippy pixel to a Sprout plant-themed color.

    Preserves high-contrast eyes and glints while mapping the body
    to a smooth green gradient based on luminance.
    """
    if a < 10:
        return (r, g, b, a)

    # Use perceived luminance for a more natural mapping
    # Formula: 0.299R + 0.587G + 0.114B
    luminance = 0.299 * r + 0.587 * g + 0.114 * b

    # Preserve pure-ish black (eyes) and pure-ish white (eye glints)
    if luminance < 35:
        return (*EYE_BLACK, a)
    if luminance > 245:
        return (*EYE_WHITE, a)

    # Normalize luminance to 0..1
    t = luminance / 255.0

    if t < 0.4:
        # Shadows: blend between dark shadow and leaf green
        local_t = t / 0.4
        new_color = lerp_color(SHADOW_COLOR, MIDTONE_COLOR, local_t)
    else:
        # Highlights: blend between leaf green and light lime
        local_t = (t - 0.4) / 0.6
        new_color = lerp_color(MIDTONE_COLOR, HIGHLIGHT_COLOR, local_t)

    # Mix with original to preserve some texture/noise, but favor the new palette
    mix = 0.9
    final = tuple(int(o * (1 - mix) + n * mix) for o, n in zip((r, g, b), new_color))
    return (*final, a)  # type: ignore[return-value]


def recolor_frame(frame: Image.Image) -> Image.Image:
    """Return a recolored copy of a single frame."""
    rgba = frame.convert("RGBA")
    pixels = list(rgba.getdata())
    new_pixels = [recolor_pixel(*p) for p in pixels]
    new_frame = Image.new("RGBA", rgba.size)
    new_frame.putdata(new_pixels)
    return new_frame


def recolor_apng(source_path: Path, dest_path: Path) -> int:
    """Recolor an APNG file and save it. Returns total duration in ms."""
    source = Image.open(source_path)
    frames: list[Image.Image] = []
    durations: list[int] = []
    total_duration = 0

    for frame_index in range(getattr(source, "n_frames", 1)):
        source.seek(frame_index)
        frames.append(recolor_frame(source))
        duration = int(source.info.get("duration", 100))
        durations.append(duration)
        total_duration += duration

    if len(frames) == 1:
        frames[0].save(dest_path, format="PNG")
    else:
        frames[0].save(
            dest_path,
            format="PNG",
            save_all=True,
            append_images=frames[1:],
            duration=durations,
            loop=0,
        )

    return total_duration


def safe_import_name(name: str) -> str:
    """Convert a filename to a valid TypeScript identifier."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def generate_sprout_tsx(durations: dict[str, int]) -> str:
    """Generate the Sprout animations TypeScript module."""
    lines: list[str] = [
        "// This file is auto-generated by tools/generate-sprout-assets.py",
        "",
        "export interface Animation {",
        "  src: string;",
        "  length: number;",
        "}",
        "",
    ]

    names = sorted(durations.keys())
    for name in names:
        import_name = safe_import_name(name)
        lines.append(f'import {import_name} from "./images/animations/sprout/{name}.png";')

    lines.append("")
    lines.append("export const SPROUT_ANIMATIONS: Record<string, Animation> = {")

    for name in names:
        import_name = safe_import_name(name)
        display_name = name.replace("_", " ")
        lines.append(f"  '{display_name}': {{")
        lines.append(f"    src: {import_name},")
        lines.append(f"    length: {durations[name]},")
        lines.append("  },")

    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not CLIPPY_ANIMATIONS_DIR.exists():
        print(f"Clippy animations directory not found: {CLIPPY_ANIMATIONS_DIR}")
        return 1

    SPROUT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    SPROUT_ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    # Copy the source animation manifest for reference
    if SPROUT_ANIMATIONS_JSON.exists():
        with open(SPROUT_ANIMATIONS_JSON, "r", encoding="utf-8") as f:
            manifest = json.load(f)
        sprout_manifest_path = SPROUT_ASSETS_DIR / "animations.json"
        with open(sprout_manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)

    durations: dict[str, int] = {}
    # Only process PNG files in the base directory, skipping the 'sprout' subdirectory
    png_files = sorted(
        p for p in CLIPPY_ANIMATIONS_DIR.iterdir()
        if p.is_file() and p.suffix.lower() == ".png"
    )

    for source_path in png_files:
        dest_path = SPROUT_OUTPUT_DIR / source_path.name
        print(f"Processing {source_path.name}...")
        total_duration = recolor_apng(source_path, dest_path)
        durations[source_path.stem] = total_duration

    tsx_content = generate_sprout_tsx(durations)
    with open(SPROUT_TSX_FILE, "w", encoding="utf-8") as f:
        f.write(tsx_content)

    print(f"Generated {len(durations)} Sprout animations in {SPROUT_OUTPUT_DIR}")
    print(f"Generated TypeScript module at {SPROUT_TSX_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
