// This file is auto-generated by tools/generate-sprout-assets.py

export interface Animation {
  src: string;
  length: number;
}

import Alert from "./images/animations/sprout/Alert.png";
import CheckingSomething from "./images/animations/sprout/CheckingSomething.png";
import Congratulate from "./images/animations/sprout/Congratulate.png";
import Default from "./images/animations/sprout/Default.png";
import EmptyTrash from "./images/animations/sprout/EmptyTrash.png";
import Explain from "./images/animations/sprout/Explain.png";
import GestureDown from "./images/animations/sprout/GestureDown.png";
import GestureLeft from "./images/animations/sprout/GestureLeft.png";
import GestureRight from "./images/animations/sprout/GestureRight.png";
import GestureUp from "./images/animations/sprout/GestureUp.png";
import GetArtsy from "./images/animations/sprout/GetArtsy.png";
import GetAttention from "./images/animations/sprout/GetAttention.png";
import GetTechy from "./images/animations/sprout/GetTechy.png";
import GetWizardy from "./images/animations/sprout/GetWizardy.png";
import GoodBye from "./images/animations/sprout/GoodBye.png";
import Greeting from "./images/animations/sprout/Greeting.png";
import Hearing_1 from "./images/animations/sprout/Hearing_1.png";
import Hide from "./images/animations/sprout/Hide.png";
import Idle1_1 from "./images/animations/sprout/Idle1_1.png";
import IdleAtom from "./images/animations/sprout/IdleAtom.png";
import IdleEyeBrowRaise from "./images/animations/sprout/IdleEyeBrowRaise.png";
import IdleFingerTap from "./images/animations/sprout/IdleFingerTap.png";
import IdleHeadScratch from "./images/animations/sprout/IdleHeadScratch.png";
import IdleRopePile from "./images/animations/sprout/IdleRopePile.png";
import IdleSideToSide from "./images/animations/sprout/IdleSideToSide.png";
import IdleSnooze from "./images/animations/sprout/IdleSnooze.png";
import LookDown from "./images/animations/sprout/LookDown.png";
import LookDownLeft from "./images/animations/sprout/LookDownLeft.png";
import LookDownRight from "./images/animations/sprout/LookDownRight.png";
import LookLeft from "./images/animations/sprout/LookLeft.png";
import LookRight from "./images/animations/sprout/LookRight.png";
import LookUp from "./images/animations/sprout/LookUp.png";
import LookUpLeft from "./images/animations/sprout/LookUpLeft.png";
import LookUpRight from "./images/animations/sprout/LookUpRight.png";
import Print from "./images/animations/sprout/Print.png";
import Processing from "./images/animations/sprout/Processing.png";
import RestPose from "./images/animations/sprout/RestPose.png";
import Save from "./images/animations/sprout/Save.png";
import Searching from "./images/animations/sprout/Searching.png";
import SendMail from "./images/animations/sprout/SendMail.png";
import Show from "./images/animations/sprout/Show.png";
import Thinking from "./images/animations/sprout/Thinking.png";
import Wave from "./images/animations/sprout/Wave.png";
import Writing from "./images/animations/sprout/Writing.png";

export const SPROUT_ANIMATIONS: Record<string, Animation> = {
  'Alert': {
    src: Alert,
    length: 2400,
  },
  'CheckingSomething': {
    src: CheckingSomething,
    length: 6640,
  },
  'Congratulate': {
    src: Congratulate,
    length: 3680,
  },
  'Default': {
    src: Default,
    length: 100,
  },
  'EmptyTrash': {
    src: EmptyTrash,
    length: 5000,
  },
  'Explain': {
    src: Explain,
    length: 1500,
  },
  'GestureDown': {
    src: GestureDown,
    length: 2250,
  },
  'GestureLeft': {
    src: GestureLeft,
    length: 3050,
  },
  'GestureRight': {
    src: GestureRight,
    length: 3250,
  },
  'GestureUp': {
    src: GestureUp,
    length: 2800,
  },
  'GetArtsy': {
    src: GetArtsy,
    length: 4900,
  },
  'GetAttention': {
    src: GetAttention,
    length: 2650,
  },
  'GetTechy': {
    src: GetTechy,
    length: 4500,
  },
  'GetWizardy': {
    src: GetWizardy,
    length: 3680,
  },
  'GoodBye': {
    src: GoodBye,
    length: 4450,
  },
  'Greeting': {
    src: Greeting,
    length: 4450,
  },
  'Hearing 1': {
    src: Hearing_1,
    length: 5400,
  },
  'Hide': {
    src: Hide,
    length: 50,
  },
  'Idle1 1': {
    src: Idle1_1,
    length: 7300,
  },
  'IdleAtom': {
    src: IdleAtom,
    length: 4500,
  },
  'IdleEyeBrowRaise': {
    src: IdleEyeBrowRaise,
    length: 1500,
  },
  'IdleFingerTap': {
    src: IdleFingerTap,
    length: 1150,
  },
  'IdleHeadScratch': {
    src: IdleHeadScratch,
    length: 1900,
  },
  'IdleRopePile': {
    src: IdleRopePile,
    length: 7500,
  },
  'IdleSideToSide': {
    src: IdleSideToSide,
    length: 5700,
  },
  'IdleSnooze': {
    src: IdleSnooze,
    length: 13600,
  },
  'LookDown': {
    src: LookDown,
    length: 1800,
  },
  'LookDownLeft': {
    src: LookDownLeft,
    length: 1800,
  },
  'LookDownRight': {
    src: LookDownRight,
    length: 1800,
  },
  'LookLeft': {
    src: LookLeft,
    length: 1800,
  },
  'LookRight': {
    src: LookRight,
    length: 1800,
  },
  'LookUp': {
    src: LookUp,
    length: 1800,
  },
  'LookUpLeft': {
    src: LookUpLeft,
    length: 1800,
  },
  'LookUpRight': {
    src: LookUpRight,
    length: 1800,
  },
  'Print': {
    src: Print,
    length: 8400,
  },
  'Processing': {
    src: Processing,
    length: 3800,
  },
  'RestPose': {
    src: RestPose,
    length: 100,
  },
  'Save': {
    src: Save,
    length: 5530,
  },
  'Searching': {
    src: Searching,
    length: 8100,
  },
  'SendMail': {
    src: SendMail,
    length: 6800,
  },
  'Show': {
    src: Show,
    length: 50,
  },
  'Thinking': {
    src: Thinking,
    length: 4500,
  },
  'Wave': {
    src: Wave,
    length: 4900,
  },
  'Writing': {
    src: Writing,
    length: 8400,
  },
};
